dont-edit-this:
  version: 7
mode: "CHAMPIONSHIP"
max-players: 100
whitelist: [ ]
live-api: ""
live-api-enabled: false
client-verify-api: ""
client-verify-whitelist: [ ]
enable-client-check: true
weighted-score: false
strict-spectator-rule: false
chat:
  refugee: "&7[&c&l裁判组&7] &f%s&7:&f %s"
  player: "&8[%team%&8] &f%s&7:&f %s"
  spectator: "&8[&7旁观&8] &7%s&7:&7 %s"
database:
  type: "MARIADB"
  address: "127.0.0.1"
  port: 3306
  name: "wcc"
  username: "root"
  password: "password"
team:
  max-members: 4
lobby:
  location:
    ==: org.bukkit.Location
    world: world
    x: 0.0
    y: 60.0
    z: 0.0
    pitch: 0.0
    yaw: 0.0